apiVersion: v1
kind: Pod
metadata:
  name: nginx-backend
  labels:
    tier: backend
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    tier: backend
