apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devopsjamssdt12
  region: us-west-2

managedNodeGroups:
  - name: managed-ng-public1
    instanceType: t2.medium
    minSize: 2
    desiredCapacity: 3
    maxSize: 4
    volumeSize: 20
    labels: {tier: frontend}
    tags:
      nodegroup-role: worker

  - name: managed-ng-public2
    instanceType: t2.medium
    minSize: 2
    desiredCapacity: 3
    maxSize: 4
    volumeSize: 20
    labels: {tier: backend}
    tags:
      nodegroup-role: backend
