apiVersion: v1
kind: Pod
metadata:
  name: nginx-frontend
  labels:
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    tier: frontend
 
